"""Public framework-light contracts for outlabs-whatsapp."""

from outlabs_whatsapp.commands import (
    InteractiveButtonsCommand,
    OutboundCommand,
    ReplyButton,
    TemplateBodyComponent,
    TemplateButtonComponent,
    TemplateCommand,
    TemplatePayloadParameter,
    TemplateTextParameter,
    TextCommand,
)
from outlabs_whatsapp.errors import (
    AmbiguousSendError,
    AuthenticationError,
    InvalidRecipientError,
    InvalidRequestError,
    InvalidTemplateError,
    InvalidWebhookChallenge,
    InvalidWebhookSignature,
    MalformedProviderResponseError,
    MalformedWebhookPayload,
    PolicyError,
    ProviderError,
    ProviderUnavailableError,
    RateLimitedError,
    WebhookError,
    WhatsAppError,
)
from outlabs_whatsapp.events import (
    DeliveryStatus,
    InboundInteractiveEvent,
    InboundTextEvent,
    MessageStatusEvent,
    NormalizedEvent,
    UnsupportedEvent,
)
from outlabs_whatsapp.meta import MetaCloudClient
from outlabs_whatsapp.provider import WhatsAppProvider
from outlabs_whatsapp.results import SendResult
from outlabs_whatsapp.webhooks import (
    EventSink,
    WebhookAcceptance,
    WebhookEnvelope,
    WebhookVerifier,
    decode_envelope,
    payload_sha256,
    signature_for,
    verify_challenge,
    verify_signature,
)

__version__ = "0.1.0a1"

__all__ = [
    "AmbiguousSendError",
    "AuthenticationError",
    "DeliveryStatus",
    "EventSink",
    "InboundInteractiveEvent",
    "InboundTextEvent",
    "InteractiveButtonsCommand",
    "InvalidRecipientError",
    "InvalidRequestError",
    "InvalidTemplateError",
    "InvalidWebhookChallenge",
    "InvalidWebhookSignature",
    "MalformedProviderResponseError",
    "MalformedWebhookPayload",
    "MessageStatusEvent",
    "MetaCloudClient",
    "NormalizedEvent",
    "OutboundCommand",
    "PolicyError",
    "ProviderError",
    "ProviderUnavailableError",
    "RateLimitedError",
    "ReplyButton",
    "SendResult",
    "TemplateBodyComponent",
    "TemplateButtonComponent",
    "TemplateCommand",
    "TemplatePayloadParameter",
    "TemplateTextParameter",
    "TextCommand",
    "UnsupportedEvent",
    "WebhookAcceptance",
    "WebhookEnvelope",
    "WebhookError",
    "WebhookVerifier",
    "WhatsAppError",
    "WhatsAppProvider",
    "decode_envelope",
    "payload_sha256",
    "signature_for",
    "verify_challenge",
    "verify_signature",
]
